#!/bin/bash

# shellcheck disable=SC2164
cd /root/gofaxip-bridge/fax_notify

if [ $# -lt 2 ]; then
    echo "Usage: $0 <qfile> <why>"
    exit 1
fi

qfile="$1"
why="$2"

# Load environment variables from .env file
set -o allexport
source .env
set +o allexport

# Define an array of "why" values that should trigger the fax_notify script
fax_notify_whys=("removed" "killed")

# Check if the "why" value is in the array
# shellcheck disable=SC2199
# shellcheck disable=SC2076
if [[ " ${fax_notify_whys[@]} " =~ " $why " ]]; then
    # Run the fax_notify Go binary for "removed" or "killed"
    ./fax_notify "$qfile" "$why"
fi